<?php

/**
 * @file
 * owlcarousel_colorbox.module
 */

/**
 * Return Owl Carousel Colorbox settings.
 */
function _owlcarousel_colorbox_settings($instance) {
  $function = !module_exists('variable') ? 'variable_get' : 'variable_get_value';

  return array(
    'colorbox' => (boolean)$function('owlcarousel_colorbox_' . $instance),
    'colorbox_imagestyle' => $function('owlcarousel_colorbox_imagestyle_' . $instance)
  );
}

/**
 * Implements hook_theme_registry_alter().
 */
function owlcarousel_colorbox_theme_registry_alter(&$theme_registry) {
  $path = drupal_get_path('module', 'owlcarousel_colorbox');

  $theme_registry['owlcarousel_list_item'] = array(
    'function' => 'theme_owlcarousel_colorbox_list_item',
    'includes' => array($path . '/theme/owlcarousel_colorbox.theme.inc'),
    'theme path' => $path . '/theme'
  );
}

/**
 * Implements hook_owlcarousel_pre_render().
 */
function owlcarousel_colorbox_owlcarousel_pre_render_alter(&$variables) {
  $id = $variables['#output']['settings']['id'];
  $instance = $variables['#output']['settings']['instance'];
  $settings = _owlcarousel_colorbox_settings($instance);

  // Attach the Colorbox settings.
  if ($settings['colorbox']) {
    $variables['#attached']['js'][] = array(
      'data' => drupal_get_path('module', 'owlcarousel_colorbox') . '/js/owlcarousel_colorbox.settings.js',
      'type' => 'file',
      'scope' => 'footer'
    );
    $variables['#attached']['js'][] = array(
      'data' => array(
        'owlcarousel_colorbox' => array(
          $id => array(
            'settings' => $settings
          )
        )
      ),
      'type' => 'setting'
    );
  }
}
