<?php

/**
 * @file
 * owlcarousel_views.module
 */

/**
 * Implements hook_views_api().
 */
function owlcarousel_views_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_menu().
 */
function owlcarousel_views_menu() {
  $items['owlcarousel/views/ajax'] = array(
    'title' => 'Owl Carousel',
    'page callback' => 'owlcarousel_views_ajax',
    'delivery callback' => 'drupal_json_output',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Menu callback, load next row (slide) by ajax.
 */
function owlcarousel_views_ajax() {
  $name = $_REQUEST['view_name'];
  $display_id = $_REQUEST['view_display_id'];
  $page = $_REQUEST['page'];

  $view = views_get_view($name);
  $view->set_display($display_id);
  $view->set_current_page($page + 1);
  $view->pre_execute();
  $view->execute();
  $view->preview();

  $rows = array();
  foreach ($view->result as $index => $row) {
    $view->row_index = $index;
    $renderer = $view->style_plugin->row_plugin;
    // Render view row results.
    $rows[] = $renderer->render($row);
  }

  drupal_json_output($rows);
}
